### ISSUE TITLE
Mismatch between config variable names and network constructor arguments

### ISSUE THREAD

**Issue by mateoespinosa** [lupalab/posterior-matching#1]
Hi @rystrauss, thank you for such an amazing repository. I've found it very easy to begin working with this library after cloning it, so I really appreciate the time and effort spent in making it very usable (if anything getting JAX to work correctly with my GPU setup was the hardest part). While trying to recreate some of the paper's experiments, I noticed a bit of a strange behaviour when changing the network's encoder or decoder parameters in some of the configs in the repo. In short, it seemed like some of the results did not change when varying the configuration of the encoders and decoders for some of the configs.

After some digging, I noticed that in [`vae.py`](https://github.com/lupalab/posterior-matching/blob/a0bdb2c44d38dfe13811c29c4482e69662d72bb4/posterior_matching/models/vae.py) (and similarly for [`vade.py`](https://github.com/lupalab/posterior-matching/blob/a0bdb2c44d38dfe13811c29c4482e69662d72bb4/posterior_matching/models/vade.py)) the encoder's parameters are passed via the `encoder_net_config` argument and the decoder's parameters are passed via the `decoder_net_config` argument. However, several of the configs in this repository actually use `encoder_config` and `decoder_config` to pass these parameters, leading to the network constructors pretty much ignoring these parameters and using the default values instead. Because every argument in these constructors has a default value, it is hard to notice this is happening as no error would be thrown.

The configs that seem to be affected are:
```bash
$ grep -r -E '(encoder_config)|(decoder_config)' configs/ -l
configs/pm_vae_bsds.py
configs/pm_vae_gas.py
configs/pm_vae_hepmass.py
configs/pm_vae_miniboone.py
configs/pm_vae_power.py
```

Fixing this would just require a simple parameter name change in those configs so this is not a big issue. I am happy to fix it myself and make a PR but I wasn't sure what the contribution policy was for this repository. In the meantime, I thought that just raising a ticket may save time for others using this repository in case they stumble upon this issue. Thanks so much again for such a wonderful library!

**Comment by rystrauss** [comment]
Hi @mateoespinosa, glad you've found the repo useful. Thank you for catching this very subtle bug and for your thorough description of the problem. I merged a pull request (#2) that I believe should solve the issue, but feel free to reopen this issue if I missed something or if you continue to have problems.
